import {Router} from 'express'
import {z} from 'zod'
import {pool,query} from '../config/database'
import {authenticate,authorize} from '../middleware/auth'
import {asyncHandler} from '../utils/asyncHandler'
import {AppError} from '../utils/errors'
import {audit} from '../services/audit'

const router=Router();router.use(authenticate)
router.get('/student',authorize('STUDENT'),asyncHandler(async(req,res)=>{const [evaluations,surveys]=await Promise.all([query(`SELECT ev.id,ev.title,ev.description,ev.type,ev.due_at event_date,'EVALUATION' kind,c.id course_id,c.title course_title,NULL::boolean responded FROM evaluations ev JOIN courses c ON c.id=ev.course_id JOIN enrollments e ON e.course_id=c.id WHERE e.user_id=$1 AND ev.is_published=true ORDER BY ev.due_at`,[req.user!.id]),query(`SELECT s.id,s.title,s.description,'SURVEY' type,s.closes_at event_date,'SURVEY' kind,c.id course_id,c.title course_title,EXISTS(SELECT 1 FROM survey_responses sr WHERE sr.survey_id=s.id AND sr.user_id=$1) responded FROM surveys s JOIN courses c ON c.id=s.course_id JOIN enrollments e ON e.course_id=c.id WHERE e.user_id=$1 AND s.is_published=true ORDER BY s.closes_at`,[req.user!.id])]);res.json({success:true,data:[...evaluations.rows,...surveys.rows].sort((a,b)=>new Date(String(a.event_date)).getTime()-new Date(String(b.event_date)).getTime())})}))
router.get('/admin',authorize('ADMIN','SUPER_ADMIN'),asyncHandler(async(_req,res)=>{const [evaluations,surveys]=await Promise.all([query(`SELECT ev.id,ev.title,ev.description,ev.type,ev.due_at event_date,'EVALUATION' kind,ev.is_published,c.id course_id,c.title course_title,COUNT(es.id)::int responses FROM evaluations ev JOIN courses c ON c.id=ev.course_id LEFT JOIN evaluation_submissions es ON es.evaluation_id=ev.id GROUP BY ev.id,c.id ORDER BY ev.due_at`),query(`SELECT s.id,s.title,s.description,'SURVEY' type,s.closes_at event_date,'SURVEY' kind,s.is_published,c.id course_id,c.title course_title,COUNT(sr.id)::int responses FROM surveys s JOIN courses c ON c.id=s.course_id LEFT JOIN survey_responses sr ON sr.survey_id=s.id GROUP BY s.id,c.id ORDER BY s.closes_at`)]);res.json({success:true,data:[...evaluations.rows,...surveys.rows].sort((a,b)=>new Date(String(a.event_date)).getTime()-new Date(String(b.event_date)).getTime())})}))
router.post('/evaluations',authorize('ADMIN','SUPER_ADMIN'),asyncHandler(async(req,res)=>{const b=z.object({courseId:z.string().uuid(),title:z.string().trim().min(3),description:z.string().trim().max(1000).optional(),type:z.enum(['EXAM','PROJECT','PRACTICE','QUIZ']),dueAt:z.coerce.date(),isPublished:z.boolean().default(true)}).parse(req.body);const {rows}=await query('INSERT INTO evaluations(course_id,title,description,type,due_at,is_published,created_by) VALUES($1,$2,$3,$4,$5,$6,$7) RETURNING *',[b.courseId,b.title,b.description||null,b.type,b.dueAt,b.isPublished,req.user!.id]);await audit(req.user!.id,'EVALUATION_CREATED','evaluation',(rows[0] as {id:string}).id);res.status(201).json({success:true,data:rows[0]})}))
router.post('/surveys',authorize('ADMIN','SUPER_ADMIN'),asyncHandler(async(req,res)=>{const b=z.object({courseId:z.string().uuid(),title:z.string().trim().min(3),description:z.string().trim().max(1000).optional(),closesAt:z.coerce.date(),isPublished:z.boolean().default(true),questions:z.array(z.string().trim().min(3).max(500)).min(1).max(12)}).parse(req.body);const client=await pool.connect();try{await client.query('BEGIN');const survey=await client.query<{id:string}>('INSERT INTO surveys(course_id,title,description,closes_at,is_published,created_by) VALUES($1,$2,$3,$4,$5,$6) RETURNING id',[b.courseId,b.title,b.description||null,b.closesAt,b.isPublished,req.user!.id]);for(const [index,prompt] of b.questions.entries())await client.query('INSERT INTO survey_questions(survey_id,prompt,position) VALUES($1,$2,$3)',[survey.rows[0].id,prompt,index+1]);await client.query('COMMIT');await audit(req.user!.id,'SURVEY_CREATED','survey',survey.rows[0].id);res.status(201).json({success:true,data:{id:survey.rows[0].id}})}catch(error){await client.query('ROLLBACK');throw error}finally{client.release()}}))
router.patch('/:kind/:id/publish',authorize('ADMIN','SUPER_ADMIN'),asyncHandler(async(req,res)=>{const kind=z.enum(['evaluation','survey']).parse(req.params.kind);const {isPublished}=z.object({isPublished:z.boolean()}).parse(req.body);const table=kind==='evaluation'?'evaluations':'surveys';const {rows}=await query(`UPDATE ${table} SET is_published=$1 WHERE id=$2 RETURNING id,is_published`,[isPublished,req.params.id]);if(!rows[0])throw new AppError(404,'Actividad no encontrada');await audit(req.user!.id,isPublished?'ACADEMIC_PUBLISHED':'ACADEMIC_UNPUBLISHED',kind,String(req.params.id));res.json({success:true,data:rows[0]})}))
router.get('/surveys/:id',authorize('STUDENT'),asyncHandler(async(req,res)=>{const {rows}=await query(`SELECT s.id,s.title,s.description,s.closes_at,c.title course_title,COALESCE(json_agg(json_build_object('id',q.id,'prompt',q.prompt,'position',q.position) ORDER BY q.position) FILTER(WHERE q.id IS NOT NULL),'[]') questions FROM surveys s JOIN courses c ON c.id=s.course_id JOIN enrollments e ON e.course_id=s.course_id LEFT JOIN survey_questions q ON q.survey_id=s.id WHERE s.id=$1 AND e.user_id=$2 AND s.is_published=true GROUP BY s.id,c.id`,[req.params.id,req.user!.id]);if(!rows[0])throw new AppError(404,'Encuesta no disponible');res.json({success:true,data:rows[0]})}))
router.post('/surveys/:id/respond',authorize('STUDENT'),asyncHandler(async(req,res)=>{const {answers}=z.object({answers:z.record(z.string(),z.string().trim().min(1).max(1200))}).parse(req.body);const allowed=await query(`SELECT q.id FROM survey_questions q JOIN surveys s ON s.id=q.survey_id JOIN enrollments e ON e.course_id=s.course_id WHERE s.id=$1 AND e.user_id=$2 AND s.is_published=true AND s.closes_at>=NOW()`,[req.params.id,req.user!.id]);if(!allowed.rows.length)throw new AppError(403,'Encuesta cerrada o no disponible');if(allowed.rows.some(row=>!answers[String((row as {id:string}).id)]))throw new AppError(400,'Responde todas las preguntas');const {rows}=await query('INSERT INTO survey_responses(survey_id,user_id,answers) VALUES($1,$2,$3) ON CONFLICT(survey_id,user_id) DO UPDATE SET answers=EXCLUDED.answers,submitted_at=NOW() RETURNING id,submitted_at',[req.params.id,req.user!.id,JSON.stringify(answers)]);res.json({success:true,data:rows[0]})}))
export default router
