// @ts-nocheck Express 5's route-param union conflicts with validated scalar route IDs.
import {Router} from 'express'
import bcrypt from 'bcryptjs'
import {z} from 'zod'
import {query} from '../config/database'
import {authenticate,authorize} from '../middleware/auth'
import {asyncHandler} from '../utils/asyncHandler'
import {AppError} from '../utils/errors'
import {audit} from '../services/audit'
import type {Role} from '../types'
const router=Router();router.use(authenticate)
router.patch('/me',asyncHandler(async(req,res)=>{const b=z.object({name:z.string().min(2).max(120),avatarUrl:z.string().url().nullable().optional()}).parse(req.body);const {rows}=await query('UPDATE users SET name=$1,avatar_url=$2 WHERE id=$3 RETURNING id,name,email,role,avatar_url,is_active,created_at',[b.name,b.avatarUrl??null,req.user!.id]);res.json({success:true,data:rows[0]})}))
router.get('/',authorize('SUPER_ADMIN'),asyncHandler(async(_req,res)=>{const {rows}=await query('SELECT id,name,email,role,avatar_url,is_active,created_at FROM users ORDER BY created_at DESC');res.json({success:true,data:rows})}))
router.post('/admins',authorize('SUPER_ADMIN'),asyncHandler(async(req,res)=>{const b=z.object({name:z.string().min(2),email:z.string().email(),password:z.string().min(8)}).parse(req.body);const {rows}=await query(`INSERT INTO users(name,email,password_hash,role) VALUES($1,LOWER($2),$3,'ADMIN') RETURNING id,name,email,role,is_active,created_at`,[b.name,b.email,await bcrypt.hash(b.password,12)]);await audit(req.user!.id,'ADMIN_CREATED','user',(rows[0] as {id:string}).id);res.status(201).json({success:true,data:rows[0]})}))
router.patch('/:id/role',authorize('SUPER_ADMIN'),asyncHandler(async(req,res)=>{const {role}=z.object({role:z.enum(['STUDENT','ADMIN'])}).parse(req.body);if(req.params.id===req.user!.id)throw new AppError(400,'No puedes cambiar tu propio rol');const target=await query<{role:Role}>('SELECT role FROM users WHERE id=$1',[req.params.id]);if(!target.rows[0])throw new AppError(404,'Usuario no encontrado');if(target.rows[0].role==='SUPER_ADMIN')throw new AppError(403,'No puedes modificar otro SUPER_ADMIN');const {rows}=await query('UPDATE users SET role=$1 WHERE id=$2 RETURNING id,name,email,role,is_active,created_at',[role,req.params.id]);await audit(req.user!.id,'USER_ROLE_CHANGED','user',req.params.id,{role});res.json({success:true,data:rows[0]})}))
router.patch('/:id/status',authorize('SUPER_ADMIN'),asyncHandler(async(req,res)=>{const {isActive}=z.object({isActive:z.boolean()}).parse(req.body);if(req.params.id===req.user!.id&&!isActive)throw new AppError(400,'No puedes desactivar tu propia cuenta');const target=await query<{role:Role}>('SELECT role FROM users WHERE id=$1',[req.params.id]);if(!target.rows[0])throw new AppError(404,'Usuario no encontrado');if(target.rows[0].role==='SUPER_ADMIN'&&!isActive){const count=await query<{count:string}>("SELECT COUNT(*) count FROM users WHERE role='SUPER_ADMIN' AND is_active=true");if(Number(count.rows[0]!.count)<=1)throw new AppError(400,'No se puede desactivar al último SUPER_ADMIN')}const {rows}=await query('UPDATE users SET is_active=$1 WHERE id=$2 RETURNING id,name,email,role,is_active,created_at',[isActive,req.params.id]);await audit(req.user!.id,isActive?'USER_ACTIVATED':'USER_DEACTIVATED','user',req.params.id);res.json({success:true,data:rows[0]})}))
router.delete('/:id',authorize('SUPER_ADMIN'),asyncHandler(async(req,res)=>{if(req.params.id===req.user!.id)throw new AppError(400,'No puedes eliminar tu propia cuenta');const target=await query<{role:Role}>('SELECT role FROM users WHERE id=$1',[req.params.id]);if(!target.rows[0])throw new AppError(404,'Usuario no encontrado');if(target.rows[0].role==='SUPER_ADMIN'){const count=await query<{count:string}>("SELECT COUNT(*) count FROM users WHERE role='SUPER_ADMIN' AND is_active=true");if(Number(count.rows[0]!.count)<=1)throw new AppError(400,'No se puede eliminar al último SUPER_ADMIN')}await query('DELETE FROM users WHERE id=$1',[req.params.id]);await audit(req.user!.id,'USER_DELETED','user',req.params.id);res.json({success:true,message:'Usuario eliminado'})}))
export default router
